### ISSUE TITLE
Setting tint color programmatically

### ISSUE THREAD

**Issue by fortuneless** [justindhill/DRPSlidingTabView#1]
setting tint color programmatically causes a crash

sample code

https://gist.github.com/fortuneless/26ec9bffe88f86e0924068c0aeacfb20

crashes on line with self.slidingTabView.tintColor = [UIColor whiteColor];

**Comment by justindhill** [comment]
Hey @fortuneless - sorry for not getting back to you sooner. I accidentally unwatched this repo and didn't get a notification about this ticket. I'll check into this

**Comment by justindhill** [comment]
Were you ever able to resolve this? I just tried to reproduce by setting the tintColor on the tab view and wasn't able to. I also added it to my storyboard as it looks like you did in your gist.
